version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: mvn dependency:resolve

      # Run tests
      - run:
          name: Run Appium tests
          command: mvn test
